name:         minoru-xmonadrc
license:      BSD3
author:       Alexander Batischev
maintainer:   Alexander Batischev <eual.jp@gmail.com>
category:     System

dependencies:
  - X11
  - X11-xft
  - base
  - xmonad
  - xmonad-contrib

ghc-options:
  - -Wall
  - -threaded
  - -O2
  - -Wno-missing-signatures # top-level signatures for XMonad settings are a pain to read and maintain

executables:
  xmonad-minoru:
    source-dirs: src
    main:        Main.hs
