resolver: lts-11.8

packages:
  - '.'

extra-deps: []
flags: {}
extra-package-dbs: []

nix:
    packages:
      - pkgconfig
      - autoconf
      - gcc
      - xorg.libX11
      - xorg.libXext
      - xorg.libXft
      - xorg.libXinerama
      - xorg.libXpm
      - xorg.libXrandr
      - xorg.libXrender
