#!/bin/sh

sudo ~/.scripts/mypassport-mount
trap 'sudo ~/.scripts/mypassport-umount' EXIT

getmail

borg create \
    -v \
    --stats \
    --progress \
    --exclude-caches --keep-exclude-tags \
    --exclude '/home/minoru/cloud' \
    --exclude 'sh:**/.git/annex/' \
    --exclude 'sh:**/.stack-work/' \
    '/media/mypassport-backup/borgbackup::{now}' \
    ~

borg prune \
    --stats \
    --progress \
    --keep-daily 180 \
    --keep-weekly 260 \
    --keep-monthly 120 \
    --keep-yearly 100 \
    /media/mypassport-backup/borgbackup
