#!/bin/sh

set -e

sudo ~/.scripts/mypassport-mount

sudo systemctl start obnam
echo "Waiting for Obnam server to start..."
sleep 3

obnam backup
sudo systemctl stop obnam

borg create \
    -v \
    --stats \
    --progress \
    --exclude-caches \
    --exclude '/home/minoru/cloud' \
    --exclude 'sh:**/.git/annex/' \
    --exclude 'sh:**/.stack-work/' \
    '/media/mypassport-backup/borgbackup::{now}' \
    ~

sudo ~/.scripts/mypassport-umount
