#!/bin/sh

set -e

sudo ~/.scripts/mypassport-mount

borg create \
    -v \
    --stats \
    --progress \
    --exclude-caches --keep-exclude-tags \
    --exclude '/home/minoru/cloud' \
    --exclude 'sh:**/.git/annex/' \
    --exclude 'sh:**/.stack-work/' \
    '/media/mypassport-backup/borgbackup::{now}' \
    ~

sudo systemctl start obnam
echo "Waiting for Obnam server to start..."
sleep 3

obnam backup || echo "Obnam exited with code $?"
sudo systemctl stop obnam

sudo ~/.scripts/mypassport-umount
