#!/bin/sh

# Fires up tmux with my favourite IM software, plus RSS and mail readers

tmux has-session -t im || (
    tmux new-session -d -s im 'torify newsbeuter'
    tmux rename-window -t im:0 newsbeuter

    # all the apps are configured to beep if something important happens, so
    # I simply disable activity monitor for the session
    tmux set-window-option -t im:newsbeuter monitor-activity off
    tmux set-option -t im -g monitor-activity off

    tmux new-window -d -n irssi -t im irssi
    tmux new-window -d -n mcabber -t im mcabber
    tmux new-window -d -n mutt -t im mutt
)

tmux attach -t im

