#!/bin/sh

# Copyright (c) 2012-2015 Alexander Batischev <eual.jp@gmail.com>
# All rights reserved.
# 
# Redistribution and use in source and binary forms, with or without
# modification, are permitted provided that the following conditions are
# met:
#     * Redistributions of source code must retain the above copyright
#       notice, this list of conditions and the following disclaimer.
#     * Redistributions in binary form must reproduce the above
#       copyright notice, this list of conditions and the following
#       disclaimer in the documentation and/or other materials provided
#       with the distribution.
#     * The names of contributors may not be used to endorse or promote
#       products derived from this software without specific prior
#       written permission.
# 
# THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS
# "AS IS" AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT
# LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR
# A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL COPYRIGHT
# HOLDER BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL,
# EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO,
# PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR
# PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF
# LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING
# NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS
# SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.

# This script is inspired by L29Ah's take on the crossposting problem:
# https://bnw.im/p/AWFP2J#KHL

if [ ! -e "$HOME/.sendxmpprc" ]; then
    echo "Please write $HOME/.sendxmpprc first!"
    exit 1
fi

sendxmpp="sendxmpp --tls --resource micropost"

postfile="`mktemp '/tmp/micropost-XXXXXXXX'`"
vim -c 'startinsert' -c 'set spell spelllang=ru_yo,en' $postfile

if [ ! -s $postfile ]; then
    # file is empty or was deleted; abort
    rm -f $postfile
    exit 1
fi

# make a backup
backupname="`date +'%Y.%m.%d %T %z.markdown'`"
backupname="$HOME/.micropost/backups/$backupname"
mkdir -p "$HOME/.micropost/backups"
cp -v "$postfile" "$backupname"

# check if any tags were specified; they should be on the first line, with
# asterisk at the beginning
tags="`head -1 $postfile | grep '^\*'`"
# body starts on the second line
body="`tail -n+2 $postfile`"

if [ -z "$tags" ]; then
    echo "No tags? Seriously? I'm quitting."
    draftname="${backupname%markdown}draft.markdown"
    mv -v "$backupname" "$draftname"
    exit 1
fi

echo -n "Posting to BNW... "
# strip leading asterisk - BNW doesn't need it
bnw_tags="`echo \"$tags\" | sed 's#^\s*\*\s*##'`"
echo "p -t $bnw_tags $body" | $sendxmpp "bnw@bnw.im" && echo "success" || echo "fail"

rm -f $postfile
