#!/bin/sh

# Runs moria logged using ttyrec

set -e

test_for() {
    if [ ! -x "$(which "$1" 2>/dev/null)" ]; then
        echo "$1 not found!"
        exit 1
    fi
}

test_for "ttyrec"
test_for "xz"

# maybe user just wants to see statistics? No need to record that
if [ "$1" = "-s" ]; then
    /usr/games/moria -s
else if [ "$1" = "-S" ]; then
    /usr/games/moria -S
else
    ttyfile=$HOME/misc/game_recordings/moria/$(date +%F-%T).ttyrec
    echo "Starting moria, logging to $ttyfile ..."
    ttyrec -e "/usr/games/moria $@" $ttyfile
    echo "Compressing $ttyfile ..."
    xz -6 $ttyfile
fi
fi
