#!/bin/sh

set -e

# Looks for and mounts my WP MyPassport, opening LUKS, enabling LVM and
# mounting partitions, then forcing Obnam locks on backup partition in case the
# device was improperly ejected and some locks weren't deleted

done_or_fail() {
    if [ $? ]; then
        echo 'done!'
    else
        echo 'fail!'
        exit $1
    fi
}

err_mypassport_connected=1
err_mypassport_luks_open=2
err_luks_open=3
err_lvchange_enable=4
err_mount=5
err_chgrp=6
err_umount=7
err_apm_fail=8

luks_dev="/dev/disk/by-uuid/8f9d8afa-60a9-4a1a-8bbb-5845395235a3"

# check if My Passport is connected
echo -n 'Looking for My Passport... '
if [ -L $luks_dev ]; then
    echo 'found!'
else
    echo 'not found!'
    exit $err_mypassport_connected
fi

# check if mypassport is already mounted. The best heuristic for that is the
# presence of the luks device - if it's present than we have luks open. The
# device under /dev/mapper is actually a symbolic link, that's why we use -L
# test
if [ -L /dev/mapper/mypassport_luks ]; then
    echo "My Passport's LUKS is already opened!"
    exit $err_mypassport_luks_open
fi

echo 'Disabling APM... '
sudo hdparm -B 255 $luks_dev
done_or_fail $err_apm_fail

# open LUKS
echo 'Opening LUKS... '
sudo cryptsetup luksOpen $luks_dev mypassport_luks
done_or_fail $err_luks_open

# activate LVM
sleep 3
echo -n 'Activating LVM... '
sudo lvm lvchange -ay mypassport_lvm
done_or_fail $err_lvchange_enable

# mount partitions
echo 'Mounting partitions...'

echo -ne '\tbackup... '
sudo mount /media/mypassport-backup
done_or_fail $err_mount

echo 'Fixing persmissions on mountpoints...'

echo -ne '\tbackup... '
sudo chgrp minoru /media/mypassport-backup
sudo chmod g+rwx /media/mypassport-backup
done_or_fail $err_chgrp
