#!/bin/sh

set -e

# Umount WD My Passport

done_or_fail() {
    if [ $? ]; then
        echo 'done!'
    else
        echo 'fail!'
        exit $1
    fi
}

err_mypassport_not_connected=1
err_mypassport_luks_open=2
err_luks_close=3
err_lvchange_enable=4
err_mount=5

luks_dev="/dev/disk/by-uuid/8f9d8afa-60a9-4a1a-8bbb-5845395235a3"

# check if mypassport is connected
echo -n 'Looking for My Passport... '
if [ -L $luks_dev ]; then
    echo 'found!'
else
    echo 'not found!'
    exit $err_mypassport_not_connected
fi

# check if mypassport is already mounted. The best heuristic for that is the
# presence of the luks device - if it's present than we have luks open. The
# device under /dev/mapper is actually a symbolic link, that's why we use -L
# test
if [ ! -b /dev/mapper/mypassport_luks ]; then
    echo "mypassport LUKS is not opened!"
    exit $err_mypassport_luks_open
fi

# umount partitions
echo 'Unmounting partitions...'

echo -n '\tbackup... '
sudo umount /media/mypassport-backup
done_or_fail $err_umount

# deactivate LVM
echo -n 'Deactivating LVM... '
sudo lvm lvchange -an mypassport_lvm
done_or_fail $err_lvchange_disable

# close LUKS
echo -n 'Closing LUKS... '
sudo cryptsetup luksClose mypassport_luks
done_or_fail $err_luks_close
