#!/bin/sh

# Umount WD My Passport

show_result() {
    if [ $? ]; then
        echo "done!"
    else
        echo "fail!"
    fi
}

err_mypassport_not_connected=1
err_mypassport_luks_open=2

luks_dev="/dev/disk/by-uuid/8f9d8afa-60a9-4a1a-8bbb-5845395235a3"

# check if mypassport is connected
echo -n 'Looking for My Passport... '
if [ -L $luks_dev ]; then
    echo 'found!'
else
    echo 'not found!'
    exit $err_mypassport_not_connected
fi

# check if mypassport is already mounted. The best heuristic for that is the
# presence of the luks device - if it's present than we have luks open. The
# device under /dev/mapper is actually a symbolic link, that's why we use -L
# test
if [ ! -b /dev/mapper/mypassport_luks ]; then
    echo "mypassport LUKS is not opened!"
    exit $err_mypassport_luks_open
fi

# umount partitions
echo 'Unmounting partitions...'

echo -n '\tbackup... '
sudo umount /media/mypassport-backup
show_result

# deactivate LVM
echo -n 'Deactivating LVM... '
sudo lvm lvchange -an mypassport_lvm
show_result

# close LUKS
echo -n 'Closing LUKS... '
sudo cryptsetup luksClose mypassport_luks
show_result

echo -n 'Spinning down the drive... '
sudo hdparm -Y $luks_dev
show_result
