#!/bin/sh

# Umount my Transcend Storejet

done_or_fail() {
    if [ $? ]; then
        echo 'done!'
    else
        echo 'fail!'
        exit $1
    fi
}

err_storejet_not_connected=1
err_storejet_luks_open=2
err_luks_close=3
err_lvchange_enable=4
err_mount=5

luks_dev="/dev/disk/by-uuid/79f20330-33b7-4ea9-b5b7-efb856aeb29e"

# check if StoreJet is connected
echo -n 'Looking for StoreJet... '
if [ -L $luks_dev ]; then
    echo 'found!'
else
    echo 'not found!'
    exit $err_storejet_not_connected
fi

# check if StoreJet is already mounted. The best heuristic for that is the
# presence of the luks device - if it's present than we have luks open. The
# device under /dev/mapper is actually a symbolic link, that's why we use -L
# test
if [ ! -b /dev/mapper/storejet_luks ]; then
    echo "Storejet LUKS is not opened!"
    exit $err_storejet_luks_open
fi

# umount partitions
echo 'Unmounting partitions...'

echo -ne '\tannex... '
sudo umount /media/storejet-annex
done_or_fail $err_umount

# deactivate LVM
echo -n 'Deactivating LVM... '
sudo lvm lvchange -an storejet_lvm
done_or_fail $err_lvchange_disable

# close LUKS
echo -n 'Closing LUKS... '
sudo cryptsetup luksClose storejet_luks
done_or_fail $err_luks_close
