#!/bin/sh

# Looks for and mounts my Transcend Storejet, opening LUKS, enabling LVM and
# mounting partitions, then forcing Obnam locks on backup partition in case the
# device was improperly ejected and some locks weren't deleted

done_or_fail() {
    if [ $? ]; then
        echo 'done!'
    else
        echo 'fail!'
        exit $1
    fi
}

err_storejet_connected=1
err_storejet_luks_open=2
err_luks_open=3
err_lvchange_enable=4
err_mount=5
err_chgrp=6
err_umount=7
err_apm_fail=8

luks_dev="/dev/disk/by-uuid/79f20330-33b7-4ea9-b5b7-efb856aeb29e"

# check if StoreJet is connected
echo -n 'Looking for StoreJet... '
if [ -L $luks_dev ]; then
    echo 'found!'
else
    echo 'not found!'
    exit $err_storejet_connected
fi

# check if StoreJet is already mounted. The best heuristic for that is the
# presence of the luks device - if it's present than we have luks open. The
# device under /dev/mapper is actually a symbolic link, that's why we use -L
# test
if [ -L /dev/mapper/storejet_luks ]; then
    echo "Storejet LUKS is already opened!"
    exit $err_storejet_luks_open
fi

echo 'Setting APM... '
sudo hdparm -B 128 $luks_dev
done_or_fail $err_apm_fail

# open LUKS
echo 'Opening LUKS... '
sudo cryptsetup luksOpen $luks_dev storejet_luks
done_or_fail $err_luks_open

# activate LVM
echo -n 'Activating LVM... '
sudo lvm lvchange -ay storejet_lvm
done_or_fail $err_lvchange_enable

# mount partitions
echo 'Mounting partitions...'

echo -ne '\tbackup... '
sudo mount /mnt/storejet-backup
done_or_fail $err_mount
echo -ne '\tannex... '
sudo mount /mnt/storejet-annex
done_or_fail $err_mount

echo 'Fixing persmissions on mountpoints...'

echo -ne '\tbackup... '
sudo chgrp minoru /mnt/storejet-backup
sudo chmod g+rwx /mnt/storejet-backup
done_or_fail $err_chgrp
echo -ne '\tannex... '
sudo chgrp minoru /mnt/storejet-annex
sudo chmod g+rwx /mnt/storejet-annex
done_or_fail $err_chgrp
