#!/bin/sh

# Put machine into hibernate

i3lock --dpms --no-unlock-indicator --image="/home/minoru/pictures/wallpapers/current.png"
if [ "$HOST" = "antaeus" ]; then
    sudo s2disk
elif [ "$HOST" = "speedy" ]; then
    sudo pm-hibernate
fi
