#!/bin/sh

# Put machine into hyrbid suspend, the one that turns into hibernate when the
# power runs out

i3lock --dpms --no-unlock-indicator --image="/home/minoru/pictures/wallpapers/current.png"
if [ "$HOST" = "antaeus" ]; then
    sudo s2both
elif [ "$HOST" = "speedy" ]; then
    sudo pm-suspend-hybrid
fi
