#!/bin/sh

# Put machine into suspend

HOST="`hostname --short`"

i3lock --dpms --no-unlock-indicator --image="/home/minoru/pictures/wallpapers/current.png"
if [ "$HOST" = "hearth" ]; then
    sudo s2ram
elif [ "$HOST" = "speedy" ]; then
    sudo pm-suspend
fi
