#!/bin/sh

# Records the tty session, storing it in the predefined directory
#
# Handy script so that I don't need to come up with the name of ttyrec file and
# a directory to save it to: it's all done automatically

recordings_dir="$HOME/misc/game_recordings"
filename="$(date +%F-%T).ttyrec"
compressor="xz -6"

command="$1"

mkdir -p "$recordings_dir/$command"
