(deftheme minoru
  "Minoru's theme")

(custom-theme-set-variables
 'minoru
 '(ansi-color-names-vector ["#272822" "#F92672" "#A6E22E" "#E6DB74" "#66D9EF" "#FD5FF0" "#A1EFE4" "#F8F8F2"])
 '(compilation-message-face (quote (quote default)))
 '(fci-rule-color "#3E3D31"))

(custom-theme-set-faces
 'minoru
 '(button ((t (:underline t))))
 '(shadow ((((class color) (min-colors 257)) (:foreground "#75715E")) (((class color) (min-colors 89)) (:foreground "#8B8878"))))
 '(match ((((class color) (min-colors 257)) (:background "#3E3D31" :foreground "#F8F8F0" :weight bold)) (((class color) (min-colors 89)) (:background "#303030" :foreground "#FFFAFA" :weight bold))))
 '(cursor ((((class color) (min-colors 257)) (:foreground "#272822" :background "#F8F8F2" :inverse-video t)) (((class color) (min-colors 89)) (:foreground "#1B1E1C" :background "#F5F5F5" :inverse-video t))))
 '(mouse ((((class color) (min-colors 257)) (:foreground "#272822" :background "#F8F8F2" :inverse-video t)) (((class color) (min-colors 89)) (:foreground "#1B1E1C" :background "#F5F5F5" :inverse-video t))))
 '(escape-glyph-face ((((class color) (min-colors 257)) (:foreground "#F92672"))))
 '(fringe ((((class color) (min-colors 257)) (:foreground "#F8F8F2" :background "#272822")) (((class color) (min-colors 89)) (:foreground "#F5F5F5" :background "#1B1E1C"))))
 '(highlight ((((class color) (min-colors 257)) (:background "#3E3D31")) (((class color) (min-colors 89)) (:background "#303030"))))
 '(link ((((class color) (min-colors 257)) (:foreground "#66D9EF" :underline t :weight bold)) (((class color) (min-colors 89)) (:foreground "#5FD7FF" :underline t :weight bold))))
 '(link-visited ((((class color) (min-colors 257)) (:foreground "#AE81FF" :underline t :weight normal)) (((class color) (min-colors 89)) (:foreground "#AF87FF" :underline t :weight normal))))
 '(success ((((class color) (min-colors 257)) (:foreground "#A6E22E")) (((class color) (min-colors 89)) (:foreground "#87D700"))))
 '(warning ((((class color) (min-colors 257)) (:foreground "#E6DB74")) (((class color) (min-colors 89)) (:foreground "#CDC673"))))
 '(error ((((class color) (min-colors 257)) (:foreground "#FD971F")) (((class color) (min-colors 89)) (:foreground "#FF8C00"))))
 '(lazy-highlight ((((class color) (min-colors 257)) (:foreground "#272822" :background "#75715E" :weight normal)) (((class color) (min-colors 89)) (:foreground "#1B1E1C" :background "#CDC673" :weight normal))))
 '(escape-glyph ((((class color) (min-colors 257)) (:foreground "#AE81FF")) (((class color) (min-colors 89)) (:foreground "#AF87FF"))))
 '(compilation-column-number ((((class color) (min-colors 257)) (:inherit font-lock-doc-face :foreground "#A1EFE4" :underline nil)) (((class color) (min-colors 89)) (:inherit font-lock-doc-face :foreground "#5FFFFF" :underline nil))))
 '(compilation-error ((((class color) (min-colors 257)) (:inherit error :underline nil)) (((class color) (min-colors 89)) (:inherit error :underline nil))))
 '(compilation-info ((((class color) (min-colors 257)) (:foreground "#75715E" :underline nil :bold nil)) (((class color) (min-colors 89)) (:foreground "#8B8878" :underline nil :bold nil))))
 '(compilation-line-number ((((class color) (min-colors 257)) (:foreground "#A6E22E" :underline nil)) (((class color) (min-colors 89)) (:foreground "#87D700" :underline nil))))
 '(compilation-warning ((((class color) (min-colors 257)) (:inherit warning :underline nil)) (((class color) (min-colors 89)) (:inherit warning :underline nil))))
 '(compilation-mode-line-exit ((((class color) (min-colors 257)) (:inherit compilation-info :foreground "#A6E22E" :weight bold)) (((class color) (min-colors 89)) (:inherit compilation-info :foreground "#87D700" :weight bold))))
 '(compilation-mode-line-fail ((((class color) (min-colors 257)) (:inherit compilation-error :foreground "#F92672" :weight bold)) (((class color) (min-colors 89)) (:inherit compilation-error :foreground "#FF1493" :weight bold))))
 '(compilation-mode-line-run ((((class color) (min-colors 257)) (:foreground "#FD971F" :weight bold)) (((class color) (min-colors 89)) (:foreground "#FF8C00" :weight bold))))
 '(diary ((((class color) (min-colors 257)) (:foreground "#E6DB74")) (((class color) (min-colors 257)) (:foreground "#CDC673"))))
 '(dired-directory ((((class color) (min-colors 257)) (:foreground "#66D9EF" :weight normal)) (((class color) (min-colors 89)) (:foreground "#5FD7FF" :weight normal))))
 '(dired-flagged ((((class color) (min-colors 257)) (:foreground "#F92672")) (((class color) (min-colors 89)) (:foreground "#FF1493"))))
 '(dired-header ((((class color) (min-colors 257)) (:foreground "#272822" :background "#66D9EF")) (((class color) (min-colors 89)) (:foreground "#1B1E1C" :background "#5FD7FF"))))
 '(dired-ignored ((((class color) (min-colors 257)) (:inherit shadow)) (((class color) (min-colors 89)) (:inherit shadow))))
 '(dired-mark ((((class color) (min-colors 257)) (:foreground "#E6DB74" :weight bold)) (((class color) (min-colors 89)) (:foreground "#CDC673" :weight bold))))
 '(dired-marked ((((class color) (min-colors 257)) (:foreground "#FD5FF0" :weight bold)) (((class color) (min-colors 89)) (:foreground "#D700D7" :weight bold))))
 '(dired-perm-write ((((class color) (min-colors 257)) (:foreground "#F8F8F2" :underline t)) (((class color) (min-colors 89)) (:foreground "#F5F5F5" :underline t))))
 '(dired-symlink ((((class color) (min-colors 257)) (:foreground "#A1EFE4" :weight normal :slant italic)) (((class color) (min-colors 89)) (:foreground "#5FFFFF" :weight normal :slant italic))))
 '(dired-warning ((((class color) (min-colors 257)) (:foreground "#FD971F" :underline t)) (((class color) (min-colors 89)) (:foreground "#FF8C00" :underline t))))
 '(isearch ((((class color) (min-colors 257)) (:foreground "#272822" :background "#AE81FF" :weight normal)) (((class color) (min-colors 89)) (:foreground "#1B1E1C" :background "#D700D7" :weight normal))))
 '(isearch-fail ((((class color) (min-colors 257)) (:foreground "#F92672" :background "#272822" :bold t)) (((class color) (min-colors 89)) (:foreground "#FF1493" :background "#1B1E1C" :bold t))))
 '(menu ((((class color) (min-colors 257)) (:foreground "#F8F8F2" :background "#272822")) (((class color) (min-colors 89)) (:foreground "#F5F5F5" :background "#1B1E1C"))))
 '(minibuffer-prompt ((((class color) (min-colors 257)) (:foreground "#66D9EF")) (((class color) (min-colors 89)) (:foreground "#5FD7FF"))))
 '(mode-line ((((class color) (min-colors 257)) (:inverse-video unspecified :underline unspecified :foreground "#F8F8F2" :background "#3E3D31" :box (:line-width 1 :color "#3E3D31" :style unspecified))) (((class color) (min-colors 89)) (:inverse-video unspecified :underline unspecified :foreground "#F5F5F5" :background "#303030" :box (:line-width 1 :color "#303030" :style unspecified)))))
 '(mode-line-buffer-id ((((class color) (min-colors 257)) (:foreground "#A6E22E" :weight bold)) (((class color) (min-colors 89)) (:foreground "#87D700" :weight bold))))
 '(mode-line-inactive ((((class color) (min-colors 257)) (:inverse-video unspecified :underline unspecified :foreground "#75715E" :background "#272822" :box (:line-width 1 :color "#3E3D31" :style unspecified))) (((class color) (min-colors 89)) (:inverse-video unspecified :underline unspecified :foreground "#8B8878" :background "#1B1E1C" :box (:line-width 1 :color "#303030" :style unspecified)))))
 '(header-line ((((class color) (min-colors 257)) (:inverse-video unspecified :underline unspecified :foreground "#F8F8F0" :background "#3E3D31" :box (:line-width 1 :color "#3E3D31" :style unspecified))) (((class color) (min-colors 89)) (:inverse-video unspecified :underline unspecified :foreground "#FFFAFA" :background "#303030" :box (:line-width 1 :color "#303030" :style unspecified)))))
 '(region ((((class color) (min-colors 257)) (:foreground "#272822" :background "#66D9EF")) (((class color) (min-colors 89)) (:foreground "#1B1E1C" :background "#5FD7FF"))))
 '(secondary-selection ((((class color) (min-colors 257)) (:background "#3E3D31")) (((class color) (min-colors 89)) (:background "#303030"))))
 '(trailing-whitespace ((((class color) (min-colors 257)) (:background "#F92672")) (((class color) (min-colors 89)) (:background "#FF1493"))))
 '(vertical-border ((((class color) (min-colors 257)) (:foreground "#3E3D31")) (((class color) (min-colors 89)) (:foreground "#303030"))))
 '(font-lock-builtin-face ((((class color) (min-colors 257)) (:foreground "#F92672" :weight normal)) (((class color) (min-colors 89)) (:foreground "#FF1493" :weight normal))))
 '(font-lock-comment-delimiter-face ((((class color) (min-colors 257)) (:foreground "#75715E")) (((class color) (min-colors 89)) (:foreground "#8B8878"))))
 '(font-lock-comment-face ((((class color) (min-colors 257)) (:foreground "#75715E")) (((class color) (min-colors 89)) (:foreground "#8B8878"))))
 '(font-lock-constant-face ((((class color) (min-colors 257)) (:foreground "#AE81FF")) (((class color) (min-colors 89)) (:foreground "#AF87FF"))))
 '(font-lock-doc-face ((((class color) (min-colors 257)) (:foreground "#75715E")) (((class color) (min-colors 89)) (:foreground "#8B8878"))))
 '(font-lock-function-name-face ((((class color) (min-colors 257)) (:foreground "#A6E22E")) (((class color) (min-colors 89)) (:foreground "#87D700"))))
 '(font-lock-keyword-face ((((class color) (min-colors 257)) (:foreground "#F92672" :weight normal)) (((class color) (min-colors 89)) (:foreground "#FF1493" :weight normal))))
 '(font-lock-negation-char-face ((((class color) (min-colors 257)) (:foreground "#E6DB74" :weight bold)) (((class color) (min-colors 89)) (:foreground "#CDC673" :weight bold))))
 '(font-lock-preprocessor-face ((((class color) (min-colors 257)) (:foreground "#F92672")) (((class color) (min-colors 89)) (:foreground "#FF1493"))))
 '(font-lock-regexp-grouping-construct ((((class color) (min-colors 257)) (:foreground "#E6DB74" :weight normal)) (((class color) (min-colors 89)) (:foreground "#CDC673" :weight normal))))
 '(font-lock-regexp-grouping-backslash ((((class color) (min-colors 257)) (:foreground "#AE81FF" :weight normal)) (((class color) (min-colors 89)) (:foreground "#AF87FF" :weight normal))))
 '(font-lock-string-face ((((class color) (min-colors 257)) (:foreground "#E6DB74")) (((class color) (min-colors 89)) (:foreground "#CDC673"))))
 '(font-lock-type-face ((((class color) (min-colors 257)) (:foreground "#66D9EF" :italic nil)) (((class color) (min-colors 89)) (:foreground "#5FD7FF" :italic nil))))
 '(font-lock-variable-name-face ((((class color) (min-colors 257)) (:foreground "#FD971F")) (((class color) (min-colors 89)) (:foreground "#FF8C00"))))
 '(font-lock-warning-face ((((class color) (min-colors 257)) (:foreground "#FD971F" :weight bold :italic t :underline t)) (((class color) (min-colors 89)) (:foreground "#FF8C00" :weight bold :italic t :underline t))))
 '(custom-face-tag ((((class color) (min-colors 257)) (:inherit variable-pitch :height 1.2 :foreground "#AE81FF" :weight bold)) (((class color) (min-colors 89)) (:inherit variable-pitch :height 1.2 :foreground "#AF87FF" :weight bold))))
 '(custom-variable-tag ((((class color) (min-colors 257)) (:inherit variable-pitch :foreground "#A1EFE4" :height 1.2)) (((class color) (min-colors 89)) (:inherit variable-pitch :foreground "#5FFFFF" :height 1.2))))
 '(custom-comment-tag ((((class color) (min-colors 257)) (:foreground "#75715E")) (((class color) (min-colors 89)) (:foreground "#8B8878"))))
 '(custom-group-tag ((((class color) (min-colors 257)) (:inherit variable-pitch :foreground "#66D9EF" :height 1.2)) (((class color) (min-colors 89)) (:inherit variable-pitch :foreground "#5FD7FF" :height 1.2))))
 '(custom-group-tag-1 ((((class color) (min-colors 257)) (:inherit variable-pitch :foreground "#F92672" :height 1.2)) (((class color) (min-colors 89)) (:inherit variable-pitch :foreground "#FF1493" :height 1.2))))
 '(custom-state ((((class color) (min-colors 257)) (:foreground "#A6E22E")) (((class color) (min-colors 89)) (:foreground "#87D700"))))
 '(flx-highlight-face ((((class color) (min-colors 257)) (:foreground "#66D9EF" :weight normal :underline nil)) (((class color) (min-colors 89)) (:foreground "#5FD7FF" :weight normal :underline nil))))
 '(helm-bookmark-directory ((((class color) (min-colors 257)) (:inherit helm-ff-directory)) (((class color) (min-colors 89)) (:inherit helm-ff-directory))))
 '(helm-bookmark-file ((((class color) (min-colors 257)) (:foreground "#F8F8F2")) (((class color) (min-colors 89)) (:foreground "#F5F5F5"))))
 '(helm-bookmark-gnus ((((class color) (min-colors 257)) (:foreground "#A1EFE4")) (((class color) (min-colors 89)) (:foreground "#5FFFFF"))))
 '(helm-bookmark-info ((((class color) (min-colors 257)) (:foreground "#A6E22E")) (((class color) (min-colors 89)) (:foreground "#87D700"))))
 '(helm-bookmark-man ((((class color) (min-colors 257)) (:foreground "#AE81FF")) (((class color) (min-colors 89)) (:foreground "#AF87FF"))))
 '(helm-bookmark-w3m ((((class color) (min-colors 257)) (:foreground "#E6DB74")) (((class color) (min-colors 89)) (:foreground "#CDC673"))))
 '(helm-buffer-not-saved ((((class color) (min-colors 257)) (:foreground "#FD971F")) (((class color) (min-colors 89)) (:foreground "#FF8C00"))))
 '(helm-buffer-saved-out ((((class color) (min-colors 257)) (:foreground "#F92672" :background "#272822" :inverse-video t)) (((class color) (min-colors 89)) (:foreground "#FF1493" :background "#1B1E1C" :inverse-video t))))
 '(helm-buffer-size ((((class color) (min-colors 257)) (:foreground "#75715E")) (((class color) (min-colors 89)) (:foreground "#8B8878"))))
 '(helm-candidate-number ((((class color) (min-colors 257)) (:background "#3E3D31" :foreground "#F8F8F0" :bold t)) (((class color) (min-colors 89)) (:background "#303030" :foreground "#FFFAFA" :bold t))))
 '(helm-ff-directory ((((class color) (min-colors 257)) (:background "#272822" :foreground "#66D9EF")) (((class color) (min-colors 89)) (:background "#1B1E1C" :foreground "#5FD7FF"))))
 '(helm-ff-executable ((((class color) (min-colors 257)) (:foreground "#A6E22E")) (((class color) (min-colors 89)) (:foreground "#87D700"))))
 '(helm-ff-file ((((class color) (min-colors 257)) (:background "#272822" :foreground "#F8F8F2")) (((class color) (min-colors 89)) (:background "#1B1E1C" :foreground "#F5F5F5"))))
 '(helm-ff-invalid-symlink ((((class color) (min-colors 257)) (:background "#272822" :foreground "#FD971F" :slant italic)) (((class color) (min-colors 89)) (:background "#1B1E1C" :foreground "#FF8C00" :slant italic))))
 '(helm-ff-prefix ((((class color) (min-colors 257)) (:background "#E6DB74" :foreground "#272822")) (((class color) (min-colors 89)) (:background "#CDC673" :foreground "#1B1E1C"))))
 '(helm-ff-symlink ((((class color) (min-colors 257)) (:foreground "#A1EFE4")) (((class color) (min-colors 89)) (:foreground "#5FFFFF"))))
 '(helm-grep-file ((((class color) (min-colors 257)) (:foreground "#A1EFE4" :underline t)) (((class color) (min-colors 89)) (:foreground "#5FFFFF" :underline t))))
 '(helm-grep-finish ((((class color) (min-colors 257)) (:foreground "#A6E22E")) (((class color) (min-colors 89)) (:foreground "#87D700"))))
 '(helm-grep-lineno ((((class color) (min-colors 257)) (:foreground "#FD971F")) (((class color) (min-colors 89)) (:foreground "#FF8C00"))))
 '(helm-grep-match ((((class color) (min-colors 257)) (:inherit match))))
 '(helm-header ((((class color) (min-colors 257)) (:inherit header-line)) (((class color) (min-colors 89)) (:inherit terminal-header-line))))
 '(helm-lisp-completion-info ((((class color) (min-colors 257)) (:foreground "#F8F8F2")) (((class color) (min-colors 89)) (:foreground "#F5F5F5"))))
 '(helm-lisp-show-completion ((((class color) (min-colors 257)) (:foreground "#E6DB74" :background "#3E3D31" :bold t)) (((class color) (min-colors 89)) (:foreground "#CDC673" :background "#303030" :bold t))))
 '(helm-M-x-key ((((class color) (min-colors 257)) (:foreground "#FD971F" :underline t)) (((class color) (min-colors 89)) (:foreground "#FF8C00" :underline t))))
 '(helm-moccur-buffer ((((class color) (min-colors 257)) (:foreground "#A1EFE4" :underline t)) (((class color) (min-colors 89)) (:foreground "#5FFFFF" :underline t))))
 '(helm-match ((((class color) (min-colors 257)) (:inherit match)) (((class color) (min-colors 89)) (:inherit match))))
 '(helm-selection ((((class color) (min-colors 257)) (:background "#3E3D31" :underline t)) (((class color) (min-colors 89)) (:background "#303030" :underline t))))
 '(helm-selection-line ((((class color) (min-colors 257)) (:background "#3E3D31" :foreground "#F8F8F0" :underline nil)) (((class color) (min-colors 89)) (:background "#303030" :foreground "#FFFAFA" :underline nil))))
 '(helm-separator ((((class color) (min-colors 257)) (:foreground "#F92672")) (((class color) (min-colors 89)) (:foreground "#FF1493"))))
 '(helm-source-header ((((class color) (min-colors 257)) (:background "#21889B" :foreground "#272822" :underline nil)) (((class color) (min-colors 89)) (:background "#87D7FF" :foreground "#1B1E1C" :underline nil))))
 '(helm-visible-mark ((((class color) (min-colors 257)) (:background "#272822" :foreground "#FD5FF0" :bold t)) (((class color) (min-colors 89)) (:background "#1B1E1C" :foreground "#D700D7" :bold t))))
 '(hl-line ((((class color) (min-colors 257)) (:background "#49483E")) (((class color) (min-colors 89)) (:background "#212121"))))
 '(ido-first-match ((((class color) (min-colors 257)) (:foreground "#E6DB74" :weight normal)) (((class color) (min-colors 89)) (:foreground "#CDC673" :weight normal))))
 '(ido-only-match ((((class color) (min-colors 257)) (:foreground "#272822" :background "#E6DB74" :weight normal)) (((class color) (min-colors 89)) (:foreground "#1B1E1C" :background "#CDC673" :weight normal))))
 '(ido-subdir ((((class color) (min-colors 257)) (:foreground "#66D9EF")) (((class color) (min-colors 89)) (:foreground "#5FD7FF"))))
 '(ido-incomplete-regexp ((((class color) (min-colors 257)) (:foreground "#F92672" :weight bold)) (((class color) (min-colors 89)) (:foreground "#FF1493" :weight bold))))
 '(ido-indicator ((((class color) (min-colors 257)) (:background "#F92672" :foreground "#272822" :width condensed)) (((class color) (min-colors 89)) (:background "#FF1493" :foreground "#1B1E1C" :width condensed))))
 '(ido-virtual ((((class color) (min-colors 257)) (:foreground "#A1EFE4")) (((class color) (min-colors 89)) (:foreground "#5FFFFF"))))
 '(js2-instance-member ((((class color) (min-colors 257)) (:foreground "#FD5FF0"))))
 '(js2-private-function-call ((((class color) (min-colors 257)) (:foreground "#E6DB74"))))
 '(linum ((((class color) (min-colors 257)) (:foreground "#75715E" :background "#272822")) (((class color) (min-colors 89)) (:foreground "#8B8878" :background "#1B1E1C"))))
 '(org-agenda-structure ((((class color) (min-colors 257)) (:foreground "#F8F8F0" :background "#3E3D31" :weight bold :slant normal :inverse-video nil :height 1.1 :underline nil :box (:line-width 2 :color "#272822"))) (((class color) (min-colors 89)) (:foreground "#FFFAFA" :background "#303030" :weight bold :slant normal :inverse-video nil :height 1.1 :underline nil :box (:line-width 2 :color "#1B1E1C")))))
 '(org-agenda-calendar-event ((((class color) (min-colors 257)) (:foreground "#F8F8F0")) (((class color) (min-colors 89)) (:foreground "#FFFAFA"))))
 '(org-agenda-calendar-sexp ((((class color) (min-colors 257)) (:foreground "#F8F8F2" :slant italic)) (((class color) (min-colors 89)) (:foreground "#F5F5F5" :slant italic))))
 '(org-agenda-date ((((class color) (min-colors 257)) (:foreground "#75715E" :background "#272822" :weight normal :inverse-video nil :overline nil :slant normal :height 1.0 :box (:line-width 2 :color "#272822"))) (((class color) (min-colors 89)) (:foreground "#8B8878" :background "#1B1E1C" :weight normal :inverse-video nil :overline nil :slant normal :height 1.0 :box (:line-width 2 :color "#1B1E1C")))))
 '(org-agenda-date-weekend ((((class color) (min-colors 257)) (:inherit org-agenda-date :inverse-video nil :background unspecified :foreground "#75715E" :weight unspecified :underline t :overline nil :box unspecified)) (((class color) (min-colors 89)) (:inherit org-agenda-date :inverse-video nil :background unspecified :foreground "#8B8878" :weight unspecified :underline t :overline nil :box unspecified))))
 '(org-agenda-date-today ((((class color) (min-colors 257)) (:inherit org-agenda-date :inverse-video t :weight bold :underline unspecified :overline nil :box unspecified :foreground "#66D9EF" :background "#272822")) (((class color) (min-colors 89)) (:inherit org-agenda-date :inverse-video t :weight bold :underline unspecified :overline nil :box unspecified :foreground "#5FD7FF" :background "#1B1E1C"))))
 '(org-agenda-done ((((class color) (min-colors 257)) (:foreground "#75715E" :slant italic)) (((class color) (min-colors 89)) (:foreground "#8B8878" :slant italic))))
 '(org-archived ((((class color) (min-colors 257)) (:foreground "#75715E" :weight normal)) (((class color) (min-colors 89)) (:foreground "#8B8878" :weight normal))))
 '(org-block ((((class color) (min-colors 257)) (:foreground "#75715E")) (((class color) (min-colors 89)) (:foreground "#8B8878"))))
 '(org-block-begin-line ((((class color) (min-colors 257)) (:foreground "#75715E" :slant italic)) (((class color) (min-colors 89)) (:foreground "#8B8878" :slant italic))))
 '(org-checkbox ((((class color) (min-colors 257)) (:background "#272822" :foreground "#F8F8F2" :box (:line-width 1 :style released-button))) (((class color) (min-colors 89)) (:background "#1B1E1C" :foreground "#F5F5F5" :box (:line-width 1 :style released-button)))))
 '(org-code ((((class color) (min-colors 257)) (:foreground "#75715E")) (((class color) (min-colors 89)) (:foreground "#8B8878"))))
 '(org-date ((((class color) (min-colors 257)) (:foreground "#66D9EF" :underline t)) (((class color) (min-colors 89)) (:foreground "#5FD7FF" :underline t))))
 '(org-done ((((class color) (min-colors 257)) (:weight bold :foreground "#A6E22E")) (((class color) (min-colors 89)) (:weight bold :foreground "#87D700"))))
 '(org-ellipsis ((((class color) (min-colors 257)) (:foreground "#75715E")) (((class color) (min-colors 89)) (:foreground "#8B8878"))))
 '(org-formula ((((class color) (min-colors 257)) (:foreground "#E6DB74")) (((class color) (min-colors 89)) (:foreground "#CDC673"))))
 '(org-headline-done ((((class color) (min-colors 257)) (:foreground "#A6E22E")) (((class color) (min-colors 89)) (:foreground "#87D700"))))
 '(org-hide ((((class color) (min-colors 257)) (:foreground "#272822")) (((class color) (min-colors 89)) (:foreground "#1B1E1C"))))
 '(org-level-1 ((((class color) (min-colors 257)) (:inherit variable-pitch :height 1.3 :foreground "#FD971F")) (((class color) (min-colors 89)) (:inherit variable-pitch :height 1.3 :foreground "#FF8C00"))))
 '(org-level-2 ((((class color) (min-colors 257)) (:inherit variable-pitch :height 1.2 :foreground "#A6E22E")) (((class color) (min-colors 89)) (:inherit variable-pitch :height 1.2 :foreground "#87D700"))))
 '(org-level-3 ((((class color) (min-colors 257)) (:inherit variable-pitch :height 1.15 :foreground "#66D9EF")) (((class color) (min-colors 89)) (:inherit variable-pitch :height 1.15 :foreground "#5FD7FF"))))
 '(org-level-4 ((((class color) (min-colors 257)) (:inherit variable-pitch :height 1.1 :foreground "#E6DB74")) (((class color) (min-colors 89)) (:inherit variable-pitch :height 1.1 :foreground "#CDC673"))))
 '(org-level-5 ((((class color) (min-colors 257)) (:inherit variable-pitch :foreground "#A1EFE4")) (((class color) (min-colors 89)) (:inherit variable-pitch :foreground "#5FFFFF"))))
 '(org-level-6 ((((class color) (min-colors 257)) (:inherit variable-pitch :foreground "#A6E22E")) (((class color) (min-colors 89)) (:inherit variable-pitch :foreground "#87D700"))))
 '(org-level-7 ((((class color) (min-colors 257)) (:inherit variable-pitch :foreground "#F92672")) (((class color) (min-colors 89)) (:inherit variable-pitch :foreground "#FF1493"))))
 '(org-level-8 ((((class color) (min-colors 257)) (:inherit variable-pitch :foreground "#66D9EF")) (((class color) (min-colors 89)) (:inherit variable-pitch :foreground "#5FD7FF"))))
 '(org-link ((((class color) (min-colors 257)) (:foreground "#E6DB74" :underline t)) (((class color) (min-colors 89)) (:foreground "#CDC673" :underline t))))
 '(org-sexp-date ((((class color) (min-colors 257)) (:foreground "#AE81FF")) (((class color) (min-colors 89)) (:foreground "#AF87FF"))))
 '(org-scheduled ((((class color) (min-colors 257)) (:foreground "#A6E22E")) (((class color) (min-colors 89)) (:foreground "#87D700"))))
 '(org-scheduled-previously ((((class color) (min-colors 257)) (:foreground "#A1EFE4")) (((class color) (min-colors 89)) (:foreground "#5FFFFF"))))
 '(org-scheduled-today ((((class color) (min-colors 257)) (:foreground "#66D9EF" :weight normal)) (((class color) (min-colors 89)) (:foreground "#5FD7FF" :weight normal))))
 '(org-special-keyword ((((class color) (min-colors 257)) (:foreground "#75715E" :weight bold)) (((class color) (min-colors 89)) (:foreground "#8B8878" :weight bold))))
 '(org-table ((((class color) (min-colors 257)) (:foreground "#A6E22E")) (((class color) (min-colors 89)) (:foreground "#87D700"))))
 '(org-tag ((((class color) (min-colors 257)) (:weight bold)) (((class color) (min-colors 89)) (:weight bold))))
 '(org-time-grid ((((class color) (min-colors 257)) (:foreground "#75715E")) (((class color) (min-colors 89)) (:foreground "#8B8878"))))
 '(org-todo ((((class color) (min-colors 257)) (:foreground "#F92672" :weight bold))))
 '(org-upcoming-deadline ((((class color) (min-colors 257)) (:foreground "#E6DB74" :weight normal :underline nil)) (((class color) (min-colors 89)) (:foreground "#CDC673" :weight normal :underline nil))))
 '(org-warning ((((class color) (min-colors 257)) (:foreground "#FD971F" :weight normal :underline nil)) (((class color) (min-colors 89)) (:foreground "#FF8C00" :weight normal :underline nil))))
 '(org-agenda-dimmed-todo-face ((((class color) (min-colors 257)) (:foreground "#75715E")) (((class color) (min-colors 89)) (:foreground "#8B8878"))))
 '(org-agenda-restriction-lock ((((class color) (min-colors 257)) (:background "#E6DB74")) (((class color) (min-colors 89)) (:background "#CDC673"))))
 '(org-clock-overlay ((((class color) (min-colors 257)) (:background "#E6DB74")) (((class color) (min-colors 89)) (:background "#CDC673"))))
 '(org-column ((((class color) (min-colors 257)) (:background "#3E3D31" :strike-through nil :underline nil :slant normal :weight normal :inherit default)) (((class color) (min-colors 89)) (:background "#303030" :strike-through nil :underline nil :slant normal :weight normal :inherit default))))
 '(org-column-title ((((class color) (min-colors 257)) (:background "#3E3D31" :underline t :weight bold)) (((class color) (min-colors 89)) (:background "#303030" :underline t :weight bold))))
 '(org-date-selected ((((class color) (min-colors 257)) (:foreground "#F92672" :inverse-video t)) (((class color) (min-colors 89)) (:foreground "#FF1493" :inverse-video t))))
 '(org-document-info ((((class color) (min-colors 257)) (:foreground "#F8F8F2")) (((class color) (min-colors 89)) (:foreground "#F5F5F5"))))
 '(org-document-title ((((class color) (min-colors 257)) (:foreground "#F8F8F0" :weight bold :height 1.3)) (((class color) (min-colors 89)) (:foreground "#FFFAFA" :weight bold :height 1.3))))
 '(org-drawer ((((class color) (min-colors 257)) (:foreground "#A1EFE4")) (((class color) (min-colors 89)) (:foreground "#5FFFFF"))))
 '(org-footnote ((((class color) (min-colors 257)) (:foreground "#FD5FF0" :underline t)) (((class color) (min-colors 89)) (:foreground "#D700D7" :underline t))))
 '(org-mode-line-clock-overrun ((((class color) (min-colors 257)) (:inherit mode-line)) (((class color) (min-colors 89)) (:inherit mode-line))))
 '(outline-1 ((((class color) (min-colors 257)) (:inherit org-level-1)) (((class color) (min-colors 89)) (:inherit org-level-1))))
 '(outline-2 ((((class color) (min-colors 257)) (:inherit org-level-2)) (((class color) (min-colors 89)) (:inherit org-level-2))))
 '(outline-3 ((((class color) (min-colors 257)) (:inherit org-level-3)) (((class color) (min-colors 89)) (:inherit org-level-3))))
 '(outline-4 ((((class color) (min-colors 257)) (:inherit org-level-4)) (((class color) (min-colors 89)) (:inherit org-level-4))))
 '(outline-5 ((((class color) (min-colors 257)) (:inherit org-level-5)) (((class color) (min-colors 89)) (:inherit org-level-5))))
 '(outline-6 ((((class color) (min-colors 257)) (:inherit org-level-6)) (((class color) (min-colors 89)) (:inherit org-level-6))))
 '(outline-7 ((((class color) (min-colors 257)) (:inherit org-level-7)) (((class color) (min-colors 89)) (:inherit org-level-7))))
 '(outline-8 ((((class color) (min-colors 257)) (:inherit org-level-8)) (((class color) (min-colors 89)) (:inherit org-level-8))))
 '(show-paren-match ((((class color) (min-colors 257)) (:foreground "#FD971F" :background "#272822" :weight normal :inverse-video t)) (((class color) (min-colors 89)) (:foreground "#FF8C00" :background "#1B1E1C" :weight normal :inverse-video t))))
 '(show-paren-mismatch ((((class color) (min-colors 257)) (:foreground "#F92672" :background "#272822" :weight normal :inverse-video t)) (((class color) (min-colors 89)) (:foreground "#FF1493" :background "#1B1E1C" :weight normal :inverse-video t))))
 '(tooltip ((((class color) (min-colors 257)) (:background "#A6E22E" :foreground "#272822" :inherit variable-pitch))))
 '(undo-tree-visualizer-default-face ((((class color) (min-colors 257)) (:foreground "#75715E" :background "#272822")) (((class color) (min-colors 89)) (:foreground "#8B8878" :background "#1B1E1C"))))
 '(undo-tree-visualizer-unmodified-face ((((class color) (min-colors 257)) (:foreground "#A6E22E")) (((class color) (min-colors 89)) (:foreground "#87D700"))))
 '(undo-tree-visualizer-current-face ((((class color) (min-colors 257)) (:foreground "#66D9EF" :inverse-video t)) (((class color) (min-colors 89)) (:foreground "#5FD7FF" :inverse-video t))))
 '(undo-tree-visualizer-active-branch-face ((((class color) (min-colors 257)) (:foreground "#F8F8F0" :background "#272822" :weight bold)) (((class color) (min-colors 89)) (:foreground "#FFFAFA" :background "#1B1E1C" :weight bold))))
 '(undo-tree-visualizer-register-face ((((class color) (min-colors 257)) (:foreground "#E6DB74")) (((class color) (min-colors 89)) (:foreground "#CDC673"))))
 '(default ((((class color) (min-colors 257)) (:foreground "#F8F8F2" :background "#000000")) (((class color) (min-colors 89)) (:foreground "#F5F5F5" :background "#000000")))))

(provide-theme 'minoru)
